# Zeabur MySQL（覆寫為遠端連線）
spring.config.import=optional:file:./brainwave-backend/application-zeabur-local.properties,optional:file:./application-zeabur-local.properties
spring.jpa.show-sql=true
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
